spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:phoenix_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:secret}

  kafka:
    bootstrap-servers: kafka:29092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/phoenix

spring.ai:
  ollama:
    base-url: http://ollama:11434
